import type { Client, Payment, RelatedObject, TransactionData } from "./common";
import type { PurchasesResponse } from "./purchases-response";

/**
 * The Payment object generated by a successful refund of a Purchase
 * (`POST /purchases/{id}/refund/`).
 *
 * Note this is a **Payment**, not a Purchase: its `id` is a new Payment id,
 * distinct from the id of the Purchase that was refunded. The originating
 * Purchase is identified by `related_to`.
 *
 * There is **no top-level `status` field** on this object — a returned Payment
 * *is* the completed refund. The in-flight case is represented by a different
 * body shape entirely; see `RefundResponse`.
 */
export interface RefundPayment {
  /** Object type identifier */
  type: string;
  /** Object ID */
  id: string;
  /** Object creation time */
  created_on: number;
  /** Object last modification time */
  updated_on: number;
  /** Client details */
  client: Client;
  /** Payment details. For a refund, `payment_type` is `refund`. */
  payment: Payment;
  /**
   * Payment method-specific, read-only, internal transaction data.
   * Will contain information about all the transaction attempts, if available.
   */
  transaction_data: TransactionData;
  /**
   * The object type and id this object is related to, if any.
   * E.g. refund Payments are related to a specific Purchase, so this object will
   * contain `type: purchase` and `id: <purchase's id>`.
   */
  related_to: RelatedObject | null;
  /** If an explicit invoice `reference` wasn't provided, this autogenerated value will be used as a reference instead. */
  reference_generated: string;
  /** Invoice reference (max 128 characters) */
  reference: string;
  /** ID of account this Payment is associated with */
  account_id: string;
  /** Company ID */
  company_id: string;
  /** Indicates this is a test object, created using test API keys or using the merchant portal while in test mode. */
  is_test: boolean;
  /** ID of user who has created this object in the merchant portal, if applicable. */
  user_id: string | null;
  /** ID of the brand this Payment is associated with */
  brand_id: string;
}

/**
 * A `200` from `POST /purchases/{id}/refund/` carries one of two different
 * objects, and which one tells you whether the refund is finished:
 *
 * - **{@link RefundPayment}** — the refund completed. The body is the Payment
 *   generated by the refund. It has **no** `status` field.
 * - **{@link PurchasesResponse}** — the operation is taking too long on the
 *   acquirer side. The body is the original Purchase with `status` =
 *   `pending_refund`, and a `purchase.pending_refund` webhook is emitted.
 *   Completion arrives later via the `payment.refunded` callback, which delivers
 *   the Payment generated by this refund.
 *
 * Discriminate on the presence of `status`: a Purchase has one, a Payment does
 * not. Do not read `status` off the union without narrowing first — on the
 * completed-refund shape it is `undefined`, which reads as "still pending".
 */
export type RefundResponse = RefundPayment | PurchasesResponse;

/** Narrows a refund response to the in-flight Purchase (`status: "pending_refund"`) shape. */
export function isPendingRefund(
  response: RefundResponse,
): response is PurchasesResponse {
  return "status" in response;
}
